name: release

on:
  push:
    tags:
      - 'v*'
                      
jobs:
  Make_GitHub_Release:
    name   : Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
                        
    - name: Release
      id  : create_release
      uses: ncipollo/release-action@v1
      env :
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag: ${{ github.ref }}
        token: ${{ secrets.TOKEN }}
        allowUpdates: true

  Archives:
    needs: Make_GitHub_Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Prepare environment
      run : |
        cmake --version
    - name: Build achive files
      run : |
        mkdir cmake && cd cmake
        cmake -DGENERATOR=ARC ..
        make
        cpack -G TGZ
        cpack -G ZIP
    - name: Upload TGZ
      id  : TGZ
      uses: actions/upload-release-asset@v1
      env :
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with: 
       upload_url: ${{ needs.Make_GitHub_Release.outputs.upload_url }}
       asset_path: ./cmake/solver-0.1.1-Linux.tar.gz
       asset_name: Solver-${{ github.ref_name }}.tar.gz
       asset_content_type: code/tgz
       
    - name: Upload ZIP
      id  : ZIP
      uses: actions/upload-release-asset@v1
      env :
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with: 
       upload_url: ${{ needs.Make_GitHub_Release.outputs.upload_url }}
       asset_path: ./cmake/solver-0.1.1-Linux.zip
       asset_name: Solver-${{ github.ref_name }}.zip
       asset_content_type: code/zip

  Linux_Binary:
    needs: Make_GitHub_Release
    runs-on: ubuntu-latest
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Prepare environment
      run : |
        cmake --version
        sudo apt-get install rpm
    - name: Build binary files
      run : |
        mkdir cmake && cd cmake
        cmake -DGENERATOR=BIN ..
        make
        cpack -G DEB
        cpack -G RPM
        
    - name: Upload DEB
      id  : DEB
      uses: actions/upload-release-asset@v1
      env :
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with: 
       upload_url: ${{ needs.Make_GitHub_Release.outputs.upload_url }}
       asset_path: ./cmake/solver-0.1.1-Linux.deb
       asset_name: solver_app-${{ github.ref_name }}.deb
       asset_content_type: application/deb
       
    - name: Upload RPM
      id  : RPM
      uses: actions/upload-release-asset@v1
      env :
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with: 
       upload_url: ${{ needs.Make_GitHub_Release.outputs.upload_url }}
       asset_path: ./cmake/solver-0.1.1-Linux.rpm
       asset_name: solver_app-${{ github.ref_name }}.rpm
       asset_content_type: application/rpm